server:
  port: 8083
  servlet:
    context-path: /v1

spring:
  application:
    name: SpringBootDemo
  # 配置数据源

  datasource:
    url: jdbc:mysql://localhost:3306/db_demo?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: guzijian
    driver-class-name: com.mysql.cj.jdbc.Driver

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 邮箱配置
  mail:
    # 只发送不接收
    host: smtp.qq.com
    # 自己的QQ
    username: 204126329@qq.com
    # 提供的密码  不是自己的登录密码
    password: zuwhinbyavzbcbdf
    # 占用端口号
    port: 587
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 8
        #连接池最大等待时间
        max-wait: -1
        # 最大空闲等待时间
        max-idle: 8
        # 最小闲置等待时间
        min-idle: 0

# mybaits 配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.gzj.demo.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
